version: '3.1'

services:

  redmine:
    image: redmine:4.2.7
    ports:
      - 3000:3000
    volumes:
      - ./files:/usr/src/redmine/files
    environment:
      REDMINE_DB_MYSQL: db
      REDMINE_DB_PASSWORD: example
      REDMINE_SECRET_KEY_BASE: supersecretkey
    depends_on: 
      - db

  db:
    image: mysql:5.7
    restart: always
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: redmine
